### PR TITLE
extract translations from two functions with the same type

### PR DESCRIPTION
**Pull request by Suhoy95**
#7

### CODE REVIEW

**Comment by Suhoy95** [comment]
IMHO the code is a little bit complicated. I think `build<*>Entry` functions and  `get<*>Function` can be inline.

**Comment by Suhoy95** [comment]
Also i must add test cases about two similar functions

**Comment by rtymchyk** [comment]
Yes, that would be great 👍

**Comment by Suhoy95** [comment]
I'm not know CircleCI, but i try find out about it

**Comment by rtymchyk** [comment]
@Suhoy95 I enabled it for forks now, so on your next commit it should show up in the status of the PR.

**Comment by rtymchyk** [comment]
Released in https://github.com/rtymchyk/babel-plugin-extract-text/releases/tag/v0.4.0

**Pull request merged**
