### PR TITLE
fix example in README.md

### PR DESCRIPTION
**Pull request by Suhoy95**

### CODE REVIEW

**Comment by Suhoy95** [comment]
Hello, i felt bad. Today i just start update plugin in my projects. And find this. How i understand it was just partial renaming, and it should be fixed.

**Comment by Suhoy95** [comment]
If you think this shorthand acceptable, then it should fix README.md.

Because there are two vatriants of using plugin:
```
{ plugins: ['syntax-jsx', ['extract-text', { ... options ... }]] } # working now 
```

Second:
```
babel.transformFile('someCode.js', {
  plugins: [
    'syntax-jsx',
    ['babel-plugin-extract-text', { // will be error
      // ...
    }],
  ],
});
```
error on https://github.com/rtymchyk/babel-plugin-extract-text/blob/master/plugin.js#L30 ,
because there no plugin with `babel-plugin-extract-text` key

**Comment by rtymchyk** [comment]
@Suhoy95 I see do you mind fixing the readme only for now?

**Comment by Suhoy95** [comment]
Yes. It is more right way. I had misconception

**Pull request merged**
